/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.api

import com.liveagent.legacy.client.model.ContactPhone
import com.liveagent.legacy.client.model.ErrorResponse
import com.liveagent.legacy.client.core._
import com.liveagent.legacy.client.core.CollectionFormats._
import com.liveagent.legacy.client.core.ApiKeyLocations._

object ContactPhonesApi {

  def apply(baseUrl: String = "https://localhost/api/v3") = new ContactPhonesApi(baseUrl)
}

class ContactPhonesApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 200 : ContactPhone (Contact phone response)
   *   code 404 : ErrorResponse (Error response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param phone 
   */
  def getContactPhone(phone: String)(implicit apiKeyValueFromRequest: ApiKeyValueFromRequest): ApiRequest[ContactPhone] =
    ApiRequest[ContactPhone](ApiMethods.GET, baseUrl, "/contact_phones/{phone}", "application/json")
      .withApiKey(apiKeyValueFromRequest, "apikey", HEADER)
      .withPathParam("phone", phone)
      .withSuccessResponse[ContactPhone](200)
      .withErrorResponse[ErrorResponse](404)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Seq[ContactPhone] (Contact phone response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param perPage Results per page.
   * @param sortDir Sorting direction ASC or DESC
   * @param sortField 
   * @param filters Filters (json object {column:value, ...} or json array [[column,operator,value], ...])
   * @param cursor used for iteration through resultset. Cursor identifies specific page in resultset.
   */
  def getContactPhonesList(perPage: Option[Int] = None, sortDir: Option[String] = None, sortField: Option[String] = None, filters: Option[String] = None, cursor: Option[String] = None)(implicit apiKeyValueFromRequest: ApiKeyValueFromRequest): ApiRequest[Seq[ContactPhone]] =
    ApiRequest[Seq[ContactPhone]](ApiMethods.GET, baseUrl, "/contact_phones", "application/json")
      .withApiKey(apiKeyValueFromRequest, "apikey", HEADER)
      .withQueryParam("_perPage", perPage)
      .withQueryParam("_sortDir", sortDir)
      .withQueryParam("_sortField", sortField)
      .withQueryParam("_filters", filters)
      .withQueryParam("_cursor", cursor)
      .withSuccessResponse[Seq[ContactPhone]](200)
      .withDefaultErrorResponse[ErrorResponse]
      



}

