/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.api

import com.liveagent.legacy.client.model.Contact
import com.liveagent.legacy.client.model.ContactListItem
import com.liveagent.legacy.client.model.ErrorResponse
import com.liveagent.legacy.client.core._
import com.liveagent.legacy.client.core.CollectionFormats._
import com.liveagent.legacy.client.core.ApiKeyLocations._

object ContactsApi {

  def apply(baseUrl: String = "https://localhost/api/v3") = new ContactsApi(baseUrl)
}

class ContactsApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 200 : Contact (Contact was created)
   *   code 400 : ErrorResponse (Data is missing)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param contact 
   */
  def createContact(contact: Option[Contact] = None)(implicit apiKey: ApiKeyValue): ApiRequest[Contact] =
    ApiRequest[Contact](ApiMethods.POST, baseUrl, "/contacts", "application/json")
      .withApiKey(apiKey, "apikey", HEADER)
      .withBody(contact)
      .withSuccessResponse[Contact](200)
      .withErrorResponse[ErrorResponse](400)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Deletes a contact
   * 
   * Expected answers:
   *   code 200 : Any (OK response)
   *   code 404 : ErrorResponse (Contact was not found)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param contactId 
   * @param deleteTickets <u>true</u>: Delete customer from all lists and also delete all his tickets.<br> <u>false</u>: Delete customer from all lists but leave his tickets intact.
   */
  def deleteContact(contactId: String, deleteTickets: Boolean)(implicit apiKey: ApiKeyValue): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.DELETE, baseUrl, "/contacts/{contactId}", "application/json")
      .withApiKey(apiKey, "apikey", HEADER)
      .withQueryParam("deleteTickets", deleteTickets)
      .withPathParam("contactId", contactId)
      .withSuccessResponse[Any](200)
      .withErrorResponse[ErrorResponse](404)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Seq[ContactListItem] (Contact response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param page Page to display. Not used if _from is defined.
   * @param perPage Results per page. Used only if _page is used.
   * @param from Result set start. Takes precedence over _page.
   * @param to Result set end. Used only if _from is used.
   * @param sortDir Sorting direction ASC or DESC
   * @param sortField Sorting field
   * @param filters Filters (json object {column:value, ...} or json array [[column,operator,value], ...])
   */
  def getContactsList(page: Option[Int] = None, perPage: Option[Int] = None, from: Option[Int] = None, to: Option[Int] = None, sortDir: Option[String] = None, sortField: Option[String] = None, filters: Option[String] = None)(implicit apiKey: ApiKeyValue): ApiRequest[Seq[ContactListItem]] =
    ApiRequest[Seq[ContactListItem]](ApiMethods.GET, baseUrl, "/contacts", "application/json")
      .withApiKey(apiKey, "apikey", HEADER)
      .withQueryParam("_page", page)
      .withQueryParam("_perPage", perPage)
      .withQueryParam("_from", from)
      .withQueryParam("_to", to)
      .withQueryParam("_sortDir", sortDir)
      .withQueryParam("_sortField", sortField)
      .withQueryParam("_filters", filters)
      .withSuccessResponse[Seq[ContactListItem]](200)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Contact (Contact response)
   *   code 404 : ErrorResponse (Contact was not found)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param contactId 
   */
  def getSpecificContact(contactId: String)(implicit apiKey: ApiKeyValue): ApiRequest[Contact] =
    ApiRequest[Contact](ApiMethods.GET, baseUrl, "/contacts/{contactId}", "application/json")
      .withApiKey(apiKey, "apikey", HEADER)
      .withPathParam("contactId", contactId)
      .withSuccessResponse[Contact](200)
      .withErrorResponse[ErrorResponse](404)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Contact (Contact was updated)
   *   code 400 : ErrorResponse (Data is missing)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param contactId 
   * @param contact 
   */
  def patchContact(contactId: String, contact: Option[Contact] = None)(implicit apiKey: ApiKeyValue): ApiRequest[Contact] =
    ApiRequest[Contact](ApiMethods.PATCH, baseUrl, "/contacts/{contactId}", "application/json")
      .withApiKey(apiKey, "apikey", HEADER)
      .withBody(contact)
      .withPathParam("contactId", contactId)
      .withSuccessResponse[Contact](200)
      .withErrorResponse[ErrorResponse](400)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Contact (Contact was registered)
   *   code 400 : ErrorResponse (Data is missing)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param contactId 
   * @param registrationEmail 
   */
  def registerContact(contactId: String, registrationEmail: String)(implicit apiKey: ApiKeyValue): ApiRequest[Contact] =
    ApiRequest[Contact](ApiMethods.PUT, baseUrl, "/contacts/{contactId}/_register", "application/json")
      .withApiKey(apiKey, "apikey", HEADER)
      .withQueryParam("registration_email", registrationEmail)
      .withPathParam("contactId", contactId)
      .withSuccessResponse[Contact](200)
      .withErrorResponse[ErrorResponse](400)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Contact (Contact was updated)
   *   code 400 : ErrorResponse (Data is missing)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param contactId 
   * @param contact 
   */
  def updateContact(contactId: String, contact: Option[Contact] = None)(implicit apiKey: ApiKeyValue): ApiRequest[Contact] =
    ApiRequest[Contact](ApiMethods.PUT, baseUrl, "/contacts/{contactId}", "application/json")
      .withApiKey(apiKey, "apikey", HEADER)
      .withBody(contact)
      .withPathParam("contactId", contactId)
      .withSuccessResponse[Contact](200)
      .withErrorResponse[ErrorResponse](400)
      .withDefaultErrorResponse[ErrorResponse]
      



}

