/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.api

import com.liveagent.legacy.client.model.Department
import com.liveagent.legacy.client.model.ErrorResponse
import com.liveagent.legacy.client.core._
import com.liveagent.legacy.client.core.CollectionFormats._
import com.liveagent.legacy.client.core.ApiKeyLocations._

object DepartmentsApi {

  def apply(baseUrl: String = "https://localhost/api/v3") = new DepartmentsApi(baseUrl)
}

class DepartmentsApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 200 : Seq[Department] (Department response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param page Page to display. Not used if _from is defined.
   * @param perPage Results per page. Used only if _page is used.
   * @param from Result set start. Takes precedence over _page.
   * @param to Result set end. Used only if _from is used.
   * @param sortDir Sorting direction ASC or DESC
   * @param sortField Sorting field
   * @param filters Filters (json object {column:value, ...} or json array [[column,operator,value], ...])
   */
  def getDepartmentList(page: Option[Int] = None, perPage: Option[Int] = None, from: Option[Int] = None, to: Option[Int] = None, sortDir: Option[String] = None, sortField: Option[String] = None, filters: Option[String] = None)(implicit apiKey: ApiKeyValue): ApiRequest[Seq[Department]] =
    ApiRequest[Seq[Department]](ApiMethods.GET, baseUrl, "/departments", "application/json")
      .withApiKey(apiKey, "apikey", HEADER)
      .withQueryParam("_page", page)
      .withQueryParam("_perPage", perPage)
      .withQueryParam("_from", from)
      .withQueryParam("_to", to)
      .withQueryParam("_sortDir", sortDir)
      .withQueryParam("_sortField", sortField)
      .withQueryParam("_filters", filters)
      .withSuccessResponse[Seq[Department]](200)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Department (Department response)
   *   code 404 : ErrorResponse (Department was not found)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param departmentId 
   */
  def getSpecificDepartment(departmentId: String)(implicit apiKey: ApiKeyValue): ApiRequest[Department] =
    ApiRequest[Department](ApiMethods.GET, baseUrl, "/departments/{departmentId}", "application/json")
      .withApiKey(apiKey, "apikey", HEADER)
      .withPathParam("departmentId", departmentId)
      .withSuccessResponse[Department](200)
      .withErrorResponse[ErrorResponse](404)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Any (Y or N)
   *   code 404 : ErrorResponse (Department was not found)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param departmentId 
   * @param agentId 
   */
  def ifAgentIsInDepartment(departmentId: String, agentId: String)(implicit apiKey: ApiKeyValue): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.GET, baseUrl, "/departments/{departmentId}/{agentId}", "application/json")
      .withApiKey(apiKey, "apikey", HEADER)
      .withPathParam("departmentId", departmentId)
      .withPathParam("agentId", agentId)
      .withSuccessResponse[Any](200)
      .withErrorResponse[ErrorResponse](404)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Update department mail account
   * 
   * Expected answers:
   *   code 200 : Department (Department that was updated)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param departmentId 
   * @param mailAccountId 
   */
  def updateDepartmentMailAccount(departmentId: String, mailAccountId: String)(implicit apiKey: ApiKeyValue): ApiRequest[Department] =
    ApiRequest[Department](ApiMethods.PUT, baseUrl, "/departments/{departmentId}/mailAccount/{mailAccountId}", "application/json")
      .withApiKey(apiKey, "apikey", HEADER)
      .withPathParam("departmentId", departmentId)
      .withPathParam("mailAccountId", mailAccountId)
      .withSuccessResponse[Department](200)
      .withDefaultErrorResponse[ErrorResponse]
      



}

