/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.api

import com.liveagent.legacy.client.model.ErrorResponse
import com.liveagent.legacy.client.model.Group
import com.liveagent.legacy.client.core._
import com.liveagent.legacy.client.core.CollectionFormats._
import com.liveagent.legacy.client.core.ApiKeyLocations._

object GroupsApi {

  def apply(baseUrl: String = "https://localhost/api/v3") = new GroupsApi(baseUrl)
}

class GroupsApi(baseUrl: String) {

  /**
   * Create new contact group
   * 
   * Expected answers:
   *   code 200 : Group (Contact group that was created)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param group 
   */
  def createGroup(group: Option[Group] = None)(implicit apiKeyValueFromRequest: ApiKeyValueFromRequest): ApiRequest[Group] =
    ApiRequest[Group](ApiMethods.POST, baseUrl, "/groups", "application/json")
      .withApiKey(apiKeyValueFromRequest, "apikey", HEADER)
      .withBody(group)
      .withSuccessResponse[Group](200)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Deletes a contact group
   * 
   * Expected answers:
   *   code 200 : Any (OK response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param groupId 
   */
  def deleteGroup(groupId: String)(implicit apiKeyValueFromRequest: ApiKeyValueFromRequest): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.DELETE, baseUrl, "/groups/{groupId}", "application/json")
      .withApiKey(apiKeyValueFromRequest, "apikey", HEADER)
      .withPathParam("groupId", groupId)
      .withSuccessResponse[Any](200)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Seq[Group] (Contact group response)
   *   code 404 : ErrorResponse (Contact group was not found)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param groupId 
   */
  def getGroupById(groupId: String)(implicit apiKeyValueFromRequest: ApiKeyValueFromRequest): ApiRequest[Seq[Group]] =
    ApiRequest[Seq[Group]](ApiMethods.GET, baseUrl, "/groups/{groupId}", "application/json")
      .withApiKey(apiKeyValueFromRequest, "apikey", HEADER)
      .withPathParam("groupId", groupId)
      .withSuccessResponse[Seq[Group]](200)
      .withErrorResponse[ErrorResponse](404)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Seq[Group] (Contact groups response)
   *   code 206 : Seq[Group] (Contact groups response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param page Page to display. Not used if _from is defined.
   * @param perPage Results per page. Used only if _page is used.
   * @param from Result set start. Takes precedence over _page.
   * @param to Result set end. Used only if _from is used.
   */
  def getGroupsList(page: Option[Int] = None, perPage: Option[Int] = None, from: Option[Int] = None, to: Option[Int] = None)(implicit apiKeyValueFromRequest: ApiKeyValueFromRequest): ApiRequest[Seq[Group]] =
    ApiRequest[Seq[Group]](ApiMethods.GET, baseUrl, "/groups", "application/json")
      .withApiKey(apiKeyValueFromRequest, "apikey", HEADER)
      .withQueryParam("_page", page)
      .withQueryParam("_perPage", perPage)
      .withQueryParam("_from", from)
      .withQueryParam("_to", to)
      .withSuccessResponse[Seq[Group]](200)
      .withErrorResponse[Seq[Group]](206)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Seq[Group] (Contact group was updated)
   *   code 400 : ErrorResponse (Data is missing)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param groupId 
   * @param group 
   */
  def updateGroup(groupId: String, group: Option[Group] = None)(implicit apiKeyValueFromRequest: ApiKeyValueFromRequest): ApiRequest[Seq[Group]] =
    ApiRequest[Seq[Group]](ApiMethods.PUT, baseUrl, "/groups/{groupId}", "application/json")
      .withApiKey(apiKeyValueFromRequest, "apikey", HEADER)
      .withBody(group)
      .withPathParam("groupId", groupId)
      .withSuccessResponse[Seq[Group]](200)
      .withErrorResponse[ErrorResponse](400)
      .withDefaultErrorResponse[ErrorResponse]
      



}

