/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.api

import com.liveagent.legacy.client.model.ErrorResponse
import com.liveagent.legacy.client.model.PredefinedAnswer
import com.liveagent.legacy.client.core._
import com.liveagent.legacy.client.core.CollectionFormats._
import com.liveagent.legacy.client.core.ApiKeyLocations._

object PredefinedAnswersApi {

  def apply(baseUrl: String = "https://localhost/api/v3") = new PredefinedAnswersApi(baseUrl)
}

class PredefinedAnswersApi(baseUrl: String) {
  
  /**
   * Create new predefined answer
   * 
   * Expected answers:
   *   code 200 : PredefinedAnswer (Predefined answer that was created)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param predefinedAnswer 
   */
  def createPredefinedAnswer(predefinedAnswer: Option[PredefinedAnswer] = None)(implicit apiKeyValue: ApiKeyValue): ApiRequest[PredefinedAnswer] =
    ApiRequest[PredefinedAnswer](ApiMethods.POST, baseUrl, "/predefined_answers", "application/json")
      .withApiKey(apiKeyValue, "apikey", HEADER)
      .withBody(predefinedAnswer)
      .withSuccessResponse[PredefinedAnswer](200)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Deletes a predefined answer
   * 
   * Expected answers:
   *   code 200 : Any (OK response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param predefinedAnswerId 
   */
  def deletePredefinedAnswer(predefinedAnswerId: String)(implicit apiKeyValue: ApiKeyValue): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.DELETE, baseUrl, "/predefined_answers/{predefinedAnswerId}", "application/json")
      .withApiKey(apiKeyValue, "apikey", HEADER)
      .withPathParam("predefinedAnswerId", predefinedAnswerId)
      .withSuccessResponse[Any](200)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : PredefinedAnswer (Predefined answer response)
   *   code 404 : ErrorResponse (Error response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param predefinedAnswerId 
   */
  def getPredefinedAnswer(predefinedAnswerId: String)(implicit apiKeyValue: ApiKeyValue): ApiRequest[PredefinedAnswer] =
    ApiRequest[PredefinedAnswer](ApiMethods.GET, baseUrl, "/predefined_answers/{predefinedAnswerId}", "application/json")
      .withApiKey(apiKeyValue, "apikey", HEADER)
      .withPathParam("predefinedAnswerId", predefinedAnswerId)
      .withSuccessResponse[PredefinedAnswer](200)
      .withErrorResponse[ErrorResponse](404)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Expected answers:
   *   code 200 : Seq[PredefinedAnswer] (Predefined answer response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param page Page to display. Not used if _from is defined.
   * @param perPage Results per page. Used only if _page is used.
   * @param from Result set start. Takes precedence over _page.
   * @param to Result set end. Used only if _from is used.
   * @param sortDir Sorting direction ASC or DESC
   * @param sortField Sorting field
   * @param filters Filters (json object {column:value, ...} or json array [[column,operator,value], ...])
   */
  def getPredefinedAnswersList(page: Option[Int] = None, perPage: Option[Int] = None, from: Option[Int] = None, to: Option[Int] = None, sortDir: Option[String] = None, sortField: Option[String] = None, filters: Option[String] = None)(implicit apiKeyValue: ApiKeyValue): ApiRequest[Seq[PredefinedAnswer]] =
    ApiRequest[Seq[PredefinedAnswer]](ApiMethods.GET, baseUrl, "/predefined_answers", "application/json")
      .withApiKey(apiKeyValue, "apikey", HEADER)
      .withQueryParam("_page", page)
      .withQueryParam("_perPage", perPage)
      .withQueryParam("_from", from)
      .withQueryParam("_to", to)
      .withQueryParam("_sortDir", sortDir)
      .withQueryParam("_sortField", sortField)
      .withQueryParam("_filters", filters)
      .withSuccessResponse[Seq[PredefinedAnswer]](200)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Update a predefined answer
   * 
   * Expected answers:
   *   code 200 : PredefinedAnswer (Predefined answer that was updated)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param predefinedAnswerId 
   * @param cannedMessage 
   */
  def updatePredefinedAnswer(predefinedAnswerId: String, cannedMessage: Option[PredefinedAnswer] = None)(implicit apiKeyValue: ApiKeyValue): ApiRequest[PredefinedAnswer] =
    ApiRequest[PredefinedAnswer](ApiMethods.PUT, baseUrl, "/predefined_answers/{predefinedAnswerId}", "application/json")
      .withApiKey(apiKeyValue, "apikey", HEADER)
      .withBody(cannedMessage)
      .withPathParam("predefinedAnswerId", predefinedAnswerId)
      .withSuccessResponse[PredefinedAnswer](200)
      .withDefaultErrorResponse[ErrorResponse]
      



}

