/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.api

import com.liveagent.legacy.client.model.ErrorResponse
import com.liveagent.legacy.client.model.Sla
import com.liveagent.legacy.client.model.SlaHistory
import com.liveagent.legacy.client.core._
import com.liveagent.legacy.client.core.CollectionFormats._
import com.liveagent.legacy.client.core.ApiKeyLocations._

object SlasApi {

  def apply(baseUrl: String = "https://localhost/api/v3") = new SlasApi(baseUrl)
}

class SlasApi(baseUrl: String) {
  
  /**
   * Gets sla
   * 
   * Expected answers:
   *   code 200 : Sla (Sla response)
   *   code 404 : ErrorResponse (Error response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param levelId 
   */
  def getSla(levelId: String)(implicit apiKeyValue: ApiKeyValue): ApiRequest[Sla] =
    ApiRequest[Sla](ApiMethods.GET, baseUrl, "/slas/{levelId}", "application/json")
      .withApiKey(apiKeyValue, "apikey", HEADER)
      .withPathParam("levelId", levelId)
      .withSuccessResponse[Sla](200)
      .withErrorResponse[ErrorResponse](404)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Gets ticket sla history
   * 
   * Expected answers:
   *   code 200 : SlaHistory (Sla response)
   *   code 404 : ErrorResponse (Error response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   * 
   * @param ticketId 
   */
  def getSlaTicketHistory(ticketId: String)(implicit apiKeyValue: ApiKeyValue): ApiRequest[SlaHistory] =
    ApiRequest[SlaHistory](ApiMethods.GET, baseUrl, "/slas/{ticketId}/history", "application/json")
      .withApiKey(apiKeyValue, "apikey", HEADER)
      .withPathParam("ticketId", ticketId)
      .withSuccessResponse[SlaHistory](200)
      .withErrorResponse[ErrorResponse](404)
      .withDefaultErrorResponse[ErrorResponse]
      

  /**
   * Gets list of slas
   * 
   * Expected answers:
   *   code 200 : Seq[Sla] (Slas response)
   *   code 0 : ErrorResponse (Error response)
   * 
   * Available security schemes:
   *   apikey (apiKey)
   */
  def getSlasList()(implicit apiKeyValue: ApiKeyValue): ApiRequest[Seq[Sla]] =
    ApiRequest[Seq[Sla]](ApiMethods.GET, baseUrl, "/slas", "application/json")
      .withApiKey(apiKeyValue, "apikey", HEADER)
      .withSuccessResponse[Seq[Sla]](200)
      .withDefaultErrorResponse[ErrorResponse]
      



}

