/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.model

import com.liveagent.legacy.client.core.{ApiEnum, ApiModel}
import org.joda.time.DateTime
import java.util.UUID

import org.json4s.MappingException

case class CallListItem (
  id: Option[String] = None,
  ticketId: Option[String] = None,
  /* I - incoming, O - outgoing, T - internal */
  `type`: Option[CallListItemEnums.`Type`] = None,
  fromNumber: Option[String] = None,
  fromName: Option[String] = None,
  toNumber: Option[String] = None,
  toName: Option[String] = None,
  viaNumber: Option[String] = None,
  dateCreated: Option[DateTime] = None,
  dateAnswered: Option[DateTime] = None,
  dateFinished: Option[DateTime] = None,
  callDuration: Option[String] = None
) extends ApiModel

object CallListItemEnums {
    sealed trait `Type` extends ApiEnum

    object `Type` {
        case object `I` extends `Type` { val value = "I" }
        case object `O` extends `Type` { val value = "O" }
        case object `T` extends `Type` { val value = "T" }

        def fromString(value: String): `Type` = value match {
          case "I" =>
            `Type`.`I`
          case "O" =>
            `Type`.`O`
          case "T" =>
            `Type`.`T`
          case unknown =>
            throw new MappingException(s"Can't convert $unknown to `Type`")
        }
    }

}

