/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.model

import com.liveagent.legacy.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Call (
  id: String,
  ticketId: String,
  /* incoming call ('in' - default), outgoing call ('out'), internal call('int') */
  direction: Option[CallEnums.Direction] = None,
  /* O - online, F - offline, U - unknown */
  calleeStatus: Option[CallEnums.CalleeStatus] = None,
  ivrs: Option[Seq[Ivr]] = None,
  recordCall: Option[Boolean] = None,
  rerouteTime: Option[Double] = None,
  maxQueueTime: Option[Double] = None,
  maxRingTime: Option[Double] = None,
  /* Name of IVR in case the service is online. If empty, call starts ringing to agents */
  onlineIvr: Option[String] = None,
  /* Name of IVR in case the service is offline. If empty, call hangs up with not available tone */
  offlineIvr: Option[String] = None,
  /* Name of IVR while waiting in queue. If empty, default in queue music is played */
  queueIvr: Option[String] = None,
  /* Caller number */
  fromNumber: Option[String] = None,
  /* Name of the caller in case it is known */
  callerName: Option[String] = None,
  /* Callee number */
  toNumber: Option[String] = None,
  /* trunk number via which call was made / received (if applicable) */
  viaNumber: Option[String] = None
) extends ApiModel

object CallEnums {

  type Direction = Direction.Value
  type CalleeStatus = CalleeStatus.Value
  object Direction extends Enumeration {
    val In = Value("in")
    val Out = Value("out")
    val Int = Value("int")
  }

  object CalleeStatus extends Enumeration {
    val `O` = Value("O")
    val `F` = Value("F")
    val `U` = Value("U")
  }

}

