/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.model

import com.liveagent.legacy.client.core.{ApiEnum, ApiModel}

import org.json4s.MappingException

case class CallMessage (
  /* T (text), H (html), A (audio - url to audio file or fileId), S (system), N (note), NF (note file) */
  `type`: CallMessageEnums.`Type`,
  message: String,
  from_number: Option[String] = None
) extends ApiModel

object CallMessageEnums {
    sealed trait `Type` extends ApiEnum

    object `Type` {
        case object `T` extends `Type` { val value = "T" }
        case object `H` extends `Type` { val value = "H" }
        case object `A` extends `Type` { val value = "A" }
        case object `S` extends `Type` { val value = "S" }
        case object `N` extends `Type` { val value = "N" }
        case object NF extends `Type` { val value = "NF" }

        def fromString(value: String): `Type` = value match {
          case "T" =>
            `Type`.`T`
          case "H" =>
            `Type`.`H`
          case "A" =>
            `Type`.`A`
          case "S" =>
            `Type`.`S`
          case "N" =>
            `Type`.`N`
          case "NF" =>
            `Type`.NF
          case unknown =>
            throw new MappingException(s"Can't convert $unknown to `Type`")
        }
    }

}

