/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.model

    import java.time.OffsetDateTime
import com.liveagent.legacy.client.core.{ApiEnum, ApiModel}

import org.json4s.MappingException

case class ContactAllOf (
  /* V - visitor, R - registered visitor */
  `type`: Option[ContactAllOfEnums.`Type`] = None,
  /* Set automatically */
  date_created: Option[OffsetDateTime] = None,
  /* Set automatically */
  date_changed: Option[OffsetDateTime] = None
) extends ApiModel

object ContactAllOfEnums {
    sealed trait `Type` extends ApiEnum

    object `Type` {
        case object `V` extends `Type` { val value = "V" }
        case object `R` extends `Type` { val value = "R" }

        def fromString(value: String): `Type` = value match {
          case "V" =>
            `Type`.`V`
          case "R" =>
            `Type`.`R`
          case unknown =>
            throw new MappingException(s"Can't convert $unknown to `Type`")
        }
    }

}

