/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.model

import com.liveagent.legacy.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IvrChoice (
  /* DTMF symbol of choice */
  dtmf: IvrChoiceEnums.Dtmf,
  /* URL of the sound to play */
  play: Option[String] = None,
  /* Readable name of choice */
  name: Option[String] = None,
  /* Name of IVR to continue in */
  ivr: String
) extends ApiModel

object IvrChoiceEnums {

  type Dtmf = Dtmf.Value
  object Dtmf extends Enumeration {
    val `0` = Value("0")
    val `1` = Value("1")
    val `2` = Value("2")
    val `3` = Value("3")
    val `4` = Value("4")
    val `5` = Value("5")
    val `6` = Value("6")
    val `7` = Value("7")
    val `8` = Value("8")
    val `9` = Value("9")
    val `star` = Value("*")
    val `hash` = Value("#")
  }

}

