/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.model

import com.liveagent.legacy.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Message (
  id: Option[String] = None,
  userid: Option[String] = None,
  /* M - MESSAGE Y - MESSAGE_LEGACY Q - QUOTED_TEXT I - INTERNAL F - FILE T - TITLE E - END D - DISCONNECT H - HEADER R - TRANSFER S - SYSTEM U - USERAGENT G - TAG V - VOICE 1 - VOICE_INTERNAL N - NOTE L - NOTE_FILE Z - FORMFIELD A - TEXT_HEADER O - TEXT_FOOTER J - STATUS B - SPLITTED W - RANKING_FEATURE_REWARD P - RANKING_FEATURE_PUNISHMENT C - RANKING_FEATURE_COMMENT K - SYSTEM_PUBLIC X - SYSTEM_VISITOR 0 - ERROR_FOOTER 2 - MERGED 3 - INVITATION_REROUTE */
  `type`: Option[MessageEnums.`Type`] = None,
  datecreated: Option[DateTime] = None,
  /* T - TEXT H - HTML J - JSON X - TEXT_LEGACY // text with possibility of internal form links (e.g. note, ranking comment, quoted, header, footer, internal) Y - HTML_LEGACY // html with possibility of internal form links (e.g. tag) Z - JSON_LEGACY // json with possibility of internal form links (e.g. footer) */
  format: Option[MessageEnums.Format] = None,
  message: Option[String] = None,
  visibility: Option[String] = None
) extends ApiModel

object MessageEnums {

  type `Type` = `Type`.Value
  type Format = Format.Value
  object `Type` extends Enumeration {
    val `M` = Value("M")
    val `Y` = Value("Y")
    val `Q` = Value("Q")
    val `I` = Value("I")
    val `F` = Value("F")
    val `T` = Value("T")
    val `E` = Value("E")
    val `D` = Value("D")
    val `H` = Value("H")
    val `R` = Value("R")
    val `S` = Value("S")
    val `U` = Value("U")
    val `G` = Value("G")
    val `V` = Value("V")
    val `1` = Value("1")
    val `N` = Value("N")
    val `L` = Value("L")
    val `Z` = Value("Z")
    val `A` = Value("A")
    val `O` = Value("O")
    val `J` = Value("J")
    val `B` = Value("B")
    val `W` = Value("W")
    val `P` = Value("P")
    val `C` = Value("C")
    val `K` = Value("K")
    val `X` = Value("X")
    val `0` = Value("0")
    val `2` = Value("2")
    val `3` = Value("3")
  }

  object Format extends Enumeration {
    val `T` = Value("T")
    val `H` = Value("H")
    val `J` = Value("J")
    val `X` = Value("X")
    val `Y` = Value("Y")
    val `Z` = Value("Z")
  }

}

