/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.model

import com.liveagent.legacy.client.core.{ApiEnum, ApiModel}

import org.json4s.MappingException

case class PhoneNumber (
  id: String,
  /* A - API controlled number, T - Twilio number, T-O - Twilio outgoing number, D - Digitale, S - Asterisk */
  `type`: Option[PhoneNumberEnums.`Type`] = None,
  /* Prefix needed to originate call using this number */
  dial_out_prefix: Option[Int] = None,
  /* Dial out prefix in 2 or 3 digits string format according to application settings */
  dial_out_prefix_formatted: Option[String] = None,
  record_call: Option[Boolean] = None,
  number: String,
  name: Option[String] = None,
  departmentid: Option[String] = None,
  department: Option[Department] = None,
  /* A - Active, I - Inactive */
  status: Option[PhoneNumberEnums.Status] = None,
  status_message: Option[String] = None,
  /* json encoded host settings */
  host_settings: Option[String] = None,
  host: Option[String] = None,
  port: Option[String] = None,
  user: Option[String] = None,
  password: Option[String] = None,
  providerid: Option[String] = None,
  ivr: Option[String] = None
) extends ApiModel

object PhoneNumberEnums {
    sealed trait `Type` extends ApiEnum

    object `Type` {
        case object `A` extends `Type` { val value = "A" }
        case object `C` extends `Type` { val value = "C" }
        case object `T` extends `Type` { val value = "T" }
        case object TO extends `Type` { val value = "T-O" }
        case object `D` extends `Type` { val value = "D" }
        case object `S` extends `Type` { val value = "S" }

        def fromString(value: String): `Type` = value match {
          case "A" =>
            `Type`.`A`
          case "C" =>
            `Type`.`C`
          case "T" =>
            `Type`.`T`
          case "T-O" =>
            `Type`.TO
          case "D" =>
            `Type`.`D`
          case "S" =>
            `Type`.`S`
          case unknown =>
            throw new MappingException(s"Can't convert $unknown to `Type`")
        }
    }

    sealed trait Status extends ApiEnum

    object Status {
        case object `A` extends Status { val value = "A" }
        case object `I` extends Status { val value = "I" }

        def fromString(value: String): Status = value match {
          case "A" =>
            Status.`A`
          case "I" =>
            Status.`I`
          case unknown =>
            throw new MappingException(s"Can't convert $unknown to Status")
        }
    }

}

