/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.model

import com.liveagent.legacy.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PhoneNumber (
  id: String,
  /* A - API controlled number, T - Twilio number, T-O - Twilio outgoing number, D - Digitale, S - Asterisk */
  `type`: Option[PhoneNumberEnums.`Type`] = None,
  /* Prefix needed to originate call using this number */
  dialOutPrefix: Option[Int] = None,
  /* Dial out prefix in 2 or 3 digits string format according to application settings */
  dialOutPrefixFormatted: Option[String] = None,
  recordCall: Option[Boolean] = None,
  number: String,
  name: Option[String] = None,
  departmentid: Option[String] = None,
  department: Option[Department] = None,
  /* A - Active, I - Inactive */
  status: Option[PhoneNumberEnums.Status] = None,
  statusMessage: Option[String] = None,
  /* json encoded host settings */
  hostSettings: Option[String] = None,
  host: Option[String] = None,
  port: Option[String] = None,
  user: Option[String] = None,
  password: Option[String] = None,
  providerid: Option[String] = None,
  ivr: Option[String] = None
) extends ApiModel

object PhoneNumberEnums {

  type `Type` = `Type`.Value
  type Status = Status.Value
  object `Type` extends Enumeration {
    val `A` = Value("A")
    val `C` = Value("C")
    val `T` = Value("T")
    val TO = Value("T-O")
    val `D` = Value("D")
    val `S` = Value("S")
  }

  object Status extends Enumeration {
    val `A` = Value("A")
    val `I` = Value("I")
  }

}

