/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.model

import com.liveagent.legacy.client.core.{ApiEnum, ApiModel}
import org.joda.time.DateTime
import java.util.UUID

import org.json4s.MappingException

case class Setting (
  name: Option[SettingEnums.Name] = None,
  value: Option[String] = None
) extends ApiModel

object SettingEnums {
    sealed trait Name extends ApiEnum

    object Name {
        case object TIMEZONE extends Name { val value = "TIMEZONE" }
        case object RegionalSettingsIsDefault extends Name { val value = "regional_settings_is_default" }
        case object Dateformat extends Name { val value = "dateformat" }
        case object Timeformat extends Name { val value = "timeformat" }
        case object Shorttimeformat extends Name { val value = "shorttimeformat" }
        case object Thousandsseparator extends Name { val value = "thousandsseparator" }
        case object Decimalseparator extends Name { val value = "decimalseparator" }

        def fromString(value: String): Name = value match {
          case "TIMEZONE" =>
            Name.TIMEZONE
          case "regional_settings_is_default" =>
            Name.RegionalSettingsIsDefault
          case "dateformat" =>
            Name.Dateformat
          case "timeformat" =>
            Name.Timeformat
          case "shorttimeformat" =>
            Name.Shorttimeformat
          case "thousandsseparator" =>
            Name.Thousandsseparator
          case "decimalseparator" =>
            Name.Decimalseparator
          case unknown =>
            throw new MappingException(s"Can't convert $unknown to Name")
        }
    }

}

