/**
 * LiveAgent API
 * This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@qualityunit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.liveagent.legacy.client.model

    import java.time.OffsetDateTime
import com.liveagent.legacy.client.core.{ApiEnum, ApiModel}

import org.json4s.MappingException

case class Subscription (
  id: String,
  /* Default domain assigned to subscription when created (e.g. example.ladesk.com) */
  domain: Option[String] = None,
  /* Additional domain parked to this subscription (e.g. support.example.com) */
  custom_domain: Option[String] = None,
  customer_email: Option[String] = None,
  customer_name: Option[String] = None,
  company: Option[String] = None,
  date_created: Option[OffsetDateTime] = None,
  date_validity: Option[OffsetDateTime] = None,
  /* I - installing A - active S - suspended T - terminated D - deleted  */
  status: Option[SubscriptionEnums.Status] = None,
  account_id: Option[String] = None,
  cluster_id: Option[String] = None,
  task_id: Option[String] = None,
  version: Option[String] = None,
  is_latest: Option[Boolean] = None,
  product_id: Option[String] = None,
  variation_id: Option[String] = None
) extends ApiModel

object SubscriptionEnums {
    sealed trait Status extends ApiEnum

    object Status {
        case object `I` extends Status { val value = "I" }
        case object `A` extends Status { val value = "A" }
        case object `S` extends Status { val value = "S" }
        case object `T` extends Status { val value = "T" }
        case object `D` extends Status { val value = "D" }

        def fromString(value: String): Status = value match {
          case "I" =>
            Status.`I`
          case "A" =>
            Status.`A`
          case "S" =>
            Status.`S`
          case "T" =>
            Status.`T`
          case "D" =>
            Status.`D`
          case unknown =>
            throw new MappingException(s"Can't convert $unknown to Status")
        }
    }

}

